#!/bin/bash

CONTEXT="$PW_DEFAULT_CONTEXT"
FOLDER_INBOX="10 - Inbox"
FOLDER_CURRENTPROJECTS="20 - Current Projects"
FOLDER_REFERENCE="30 - Reference"
FOLDER_ARCHIVED="40 - Archived"
FOLDER_CONFIGURATION=".pw"
FOLDER_TEMPLATES="$FOLDER_CONFIGURATION/templates"
DEFAULT_TEMPLATE_NAME="default"

COMMAND=""

PW_USAGE="Usage: `basename "$0"`"