#!/bin/bash

INSTANCE="$VSTSPERSO"
PROJECTNAME="PreliminaryPudding"
PROJECTTYPE="VisualStudio"
REPONAME="${PWD##*/}"
REMOTE="origin"
INIT=1

usage() {
    echo "Usage: `basename "$0"` [--name name] [--project project-name] [--instance instance] [--type type]"
    exit 1
}

while [[ $# -gt 0 ]]
do
    key="$1"
    shift

    case $key in
        -p|--project)
            PROJECTNAME="$1"
            shift
        ;;
        -i|--instance)
            INSTANCE="$1"
            shift
        ;;
        -t|--type)
            PROJECTTYPE="$1"
            shift
        ;;
        -n|--name)
            REPONAME="$1"
            shift
        ;;
        -r|--remote)
            REMOTE="$1"
            shift
        ;;
        --no-init)
            INIT=0
        ;;
        *)
            echo "Unknown parameter: $key"
            usage
        ;;
    esac
done

if [ -z "$REPONAME" ]; then
    echo "Missing repository name"
    usage
fi

echo -e "Creating Azure Devops repo \n Instance: $INSTANCE \n Project: $PROJECTNAME \n Repository name: $REPONAME"
SSHURL=`vsts code repo create --instance "$INSTANCE" --project "$PROJECTNAME" --name "$REPONAME" --query "additionalProperties.sshUrl" | sed 's/"//g'`
if [ $? != 0 ]; then
    echo "Devops repo creation failed, aborting."
    exit
fi
echo "Initializing git"

if [ $INIT = 1 ]; then
    git init
    curl -s -o .gitignore https://raw.githubusercontent.com/github/gitignore/master/$PROJECTTYPE.gitignore > /dev/null
fi
git remote add $REMOTE $SSHURL
echo "Downloading gitignore for $PROJECTTYPE"
