#!/bin/bash

INSTANCE="$VSTSPERSO"
PROJECTNAME="PreliminaryPudding"
PROJECTTYPE="VisualStudio"
REPONAME="${PWD##*/}"
REMOTE="origin"
HOST="devops"
INIT=1

usage() {
    echo "Usage: `basename "$0"` [--host github|devops] [--name name] [--project project-name] [--instance instance] [--type type] [--no-init]"
    exit 1
}

while [[ $# -gt 0 ]]
do
    key="$1"
    shift

    case $key in
        -p|--project)
            PROJECTNAME="$1"
            shift
        ;;
        -i|--instance)
            INSTANCE="$1"
            shift
        ;;
        -t|--type)
            PROJECTTYPE="$1"
            shift
        ;;
        -n|--name)
            REPONAME="$1"
            shift
        ;;
        -r|--remote)
            REMOTE="$1"
            shift
        ;;
        --no-init)
            INIT=0
        ;;
        --host|-h)
            HOST="$1"
            shift
        ;;
        *)
            echo "Unknown parameter: $key"
            usage
        ;;
    esac
done

if [ -z "$REPONAME" ]; then
    echo "Missing repository name"
    usage
fi

if [ $HOST = "devops" ]; then
    echo -e "Creating Azure Devops repo \n Instance: $INSTANCE \n Project: $PROJECTNAME \n Repository name: $REPONAME"
    SSHURL=`vsts code repo create --instance "$INSTANCE" --project "$PROJECTNAME" --name "$REPONAME" --query "additionalProperties.sshUrl" | sed 's/"//g'`
    if [ $? != 0 ]; then
        echo "Devops repo creation failed, aborting."
        exit
    fi
fi

if [ $HOST = "github" ]; then
    echo -e "Creating GitHub repo $REPONAME"
    SSHURL=`gh repo create $REPONAME -o tsv --query ssh_url`
    if [ -z $SSHURL ]; then
        echo "Github repo creation failed, aborting."
        exit
    fi
fi

if [ $INIT = 1 ]; then
    echo "Initializing git"
    git init
    echo "Downloading gitignore for $PROJECTTYPE"
    curl -s -o .gitignore https://raw.githubusercontent.com/github/gitignore/master/$PROJECTTYPE.gitignore > /dev/null
    echo "env-*" >> .gitignore
    echo "cleanup-*" >> .gitignore
fi
git remote add $REMOTE $SSHURL
