#!/bin/bash

set -e -u

LOCAL_PATH=`dirname $0`
RES=$LOCAL_PATH/new-ws-res
HOST=
DOMAIN=
SUBDOMAIN=
REPO=
FOLDER=
RG=
STATIC_WEBSITE=
REGION=westus2

usage() {
    echo "Usage: `basename "$0"` [--host <HOST> | --folder <FOLDER> | --repo <REPO> | --resource-group <GROUP> | --help]"
    exit 1
}

if [ -z `which jq` ]; then
  echo "Error: jq is not installed"
  usage
fi

if [ -z "`which az`" ]; then
  echo "Error: azure cli is not installed"
  usage
fi

if [ -z "`which gh`" ]; then
  echo "Error: github cli is not installed"
  usage
fi

while [[ $# -gt 0 ]]
do
    key="$1"
    shift

    case $key in
        -h|--help)
            usage
        ;;
        -H|--host)
            HOST=$1
            shift
        ;;
        -r|--repo)
            REPO=$1
            shift
        ;;
        -g|--resource-group)
            RG=$1
            shift
        ;;
        -f|--folder)
            FOLDER=$1
            shift
        ;;
        *)
            echo "Error: Unknown parameter: $key"
            usage
        ;;
    esac
done

if [ -z "$HOST" ]; then
  echo "Error: Please specify a host with --host"
  usage
fi

DOMAIN=`echo $HOST | sed -E "s/[^.]+\.//"`
SUBDOMAIN=`echo $HOST | sed -E "s/\..+//"`

if [ -z "$FOLDER" ]; then
  FOLDER="$HOST"
fi

if [ -z "$REPO" ]; then
  REPO="$HOST"
fi

if [ -z "$RG" ]; then
  RG="$HOST"
fi

if [ -z "$STATIC_WEBSITE" ]; then
  STATIC_WEBSITE="$HOST"
fi

echo "## Look for DNS zone $DOMAIN"
DNS_LIST=`az network dns zone list`
DNS_ZONE=`echo $DNS_LIST | jq ".[] | select(.name == \"$DOMAIN\")"`
DNS_ZONE_RG=`echo $DNS_ZONE | jq -r ".resourceGroup"`
SUBSCRIPTION_ID=`az account show --query "id" -o tsv`

if [ -z "$DNS_ZONE_RG" ]; then
  echo "Error: No DNS zone found for $DOMAIN"
  usage
fi

echo "## Init git repo to $FOLDER and copy base"
gh repo create $REPO --private --confirm
cp -r $RES/base/.gitignore $FOLDER/
cp -r $RES/base/.github $FOLDER/
cp $RES/base/README.md $FOLDER/
cd $FOLDER
git checkout -b main
GITHUB_REPO_NAME=`gh repo view | grep "name:" | sed -E 's/name:\s+//'`

echo "## Create resource group $RG"
az group create --name $RG -l $REGION --query "properties.provisioningState" -o tsv

echo "## Create static website $STATIC_WEBSITE in resource group $RG"
RES=`az staticwebapp create -g $RG -n $STATIC_WEBSITE -l $REGION -s "" -b "" -t "none"`

STATIC_WEBSITE_RG=$RG
STATIC_WEBSITE_HOST=`echo $RES | jq -r ".defaultHostname"`

echo "## Create DNS record"
az network dns record-set cname create -g $DNS_ZONE_RG -z $DOMAIN -n $SUBDOMAIN --query "provisioningState" -o "tsv"
az network dns record-set cname set-record -g $DNS_ZONE_RG -z $DOMAIN -n $SUBDOMAIN -c "$STATIC_WEBSITE_HOST" --query "provisioningState" -o "tsv"
echo "## Add hostname to static webapp"
az staticwebapp hostname set --hostname $HOST --name $STATIC_WEBSITE
echo "## Add deployment token to github"
AZURE_STATIC_WEBSITE_TOKEN=`az rest --method post --url /subscriptions/$SUBSCRIPTION_ID/resourcegroups/$STATIC_WEBSITE_RG/providers/Microsoft.Web/staticSites/$STATIC_WEBSITE/listsecrets?api-version=2020-06-01 | jq -r ".properties.apiKey"`
gh secret set --repo $GITHUB_REPO_NAME AZURE_STATIC_WEBSITE_TOKEN -b "$AZURE_STATIC_WEBSITE_TOKEN"

echo "## Push to repo"
git add -A
git commit -m "Initial commit"
git push origin main
