#!/bin/bash

####
# Proletarian wizard
####

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
INCLUDE="$SCRIPTPATH/proletarian-wizard"

source "$INCLUDE/common-variables.sh"
source "$INCLUDE/p-usage.sh"
source "$INCLUDE/p-parse-command-line.sh"

if [ -z "$COMMAND" ]; then
  echo "Error: no command specified."
  usage_base
  exit -1
fi

if [ ! -d "$CONTEXT/$FOLDER_CURRENTPROJECT" ]; then
  echo "Error: current project folder does not exist"
  echo "Was looking for $FOLDER_CURRENTPROJECT"
  exit -1
fi

case $COMMAND in
  open)
    source $INCLUDE/p-command-open.sh
  ;;
  list)
    source $INCLUDE/p-command-list.sh
  ;;
  create)
    source $INCLUDE/p-command-create.sh
  ;;
  show)
    source $INCLUDE/p-command-show.sh
  ;;
esac
