name: Build to Azure Static

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          path: code
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
      - run: npm install plaf
      - run: ./node_modules/plaf/bin/plaf -i code -o rendered --generate-search 
      - name: Upload
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBSITE_TOKEN }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "rendered" 
          # api_location: "api" # Api source code path - optional
          output_location: "rendered" 